start = atom

atom = ignore* number:numberChar+ ignore* {return parseInt(number.join(""));}
	/ ignore* atom:atomChar+ ignore* {return atom.join("");}
	/ ignore* '\'' a:atom ignore* {return ['quote', a];}
	/ ignore* '(' exp:atom+ ')' ignore* { return exp.length == 1 ? exp[0] : exp; }

ignore = comment / ignoreChar
comment = ';;' [^\n\r]* eol
numberChar = [0-9]
atomChar = [0-9a-zA-Z_?!+=@#$%^&*/.-]
ignoreChar = [ \t\n\r]
eol = [\n\r]{1,2} / !. 